// USER LOGIN
export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const SIGN_OUT = "SIGN_OUT";

// User
export const USER_FETCH = "USER_FETCH";
export const USER_FETCH_ERROR = "USER_FETCH_ERROR";

// Event CRUD
export const EVENT_CREATE = "EVENT_CREATE";
export const EVENT_CREATE_ERROR = "EVENT_CREATE_ERROR";
export const EVENT_UPDATE = "EVENT_UPDATE";
export const EVENT_UPDATE_ERROR = "EVENT_UPDATE_ERROR";
export const EVENT_DELETE = "EVENT_DELETE";
export const EVENT_DELETE_ERROR = "EVENT_DELETE_ERROR";

// EVENTS
export const EVENTS_FETCH = "EVENTS_FETCH";
export const EVENTS_FETCH_ERROR = "EVENTS_FETCH_ERROR";

// EVENT FOR THE GUIDE
export const EVENT_GUIDE = "EVENT_GUIDE";
export const EVENT_GUIDE_ERROR = "EVENT_GUIDE_ERROR";
